# Project
version=0.18.0
group=com.baisylia.culturaldelights
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Cultural Delights
mod_author=Developer: Baisylia, Evanbones | Art: Baisylia, Raspmary, Bagels, Nive, Quoraal
mod_id=culturaldelights
license=All Rights Reserved
credits=
description=A Farmer's Delight addon that adds food systems from around the world
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Dependencies
farmers_delight_version=1.21.1-1.3.4
cooks_collection_version=0.5.6
supplementaries_version=DOZiryjL
emi_version=1.1.24+1.21.1
jei_version=19.21.0.247
appleskin_version=3.0.5+mc1.21

# NeoForge
neoforge_version=21.1.247
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
